#pragma once

/// Protocol enums referenced from bedrock-headers (BDS).
///
/// Values match the BDS C++ enum classes. Only enums used by endweave
/// handlers are defined here. See bedrock-headers for the full definitions.

#include <cstdint>

namespace endweave {

/// ActorDataIDs (enum class : uint8_t in BDS)
enum class ActorDataIDs : std::uint8_t {
    RESERVED_0 = 0,
    STRUCTURAL_INTEGRITY = 1,
    VARIANT = 2,
    COLOR_INDEX = 3,
    NAME = 4,
    OWNER = 5,
    TARGET = 6,
    AIR_SUPPLY = 7,
    EFFECT_COLOR = 8,
    RESERVED_009 = 9,
    RESERVED_010 = 10,
    HURT = 11,
    HURT_DIR = 12,
    ROW_TIME_LEFT = 13,
    ROW_TIME_RIGHT = 14,
    VALUE = 15,
    DISPLAY_TILE_RUNTIME_ID = 16,
    DISPLAY_OFFSET = 17,
    CUSTOM_DISPLAY = 18,
    SWELL = 19,
    OLD_SWELL = 20,
    SWELL_DIR = 21,
    CHARGE_AMOUNT = 22,
    DEPRECATED_CARRY_BLOCK_RUNTIME_ID = 23,
    CLIENT_EVENT = 24,
    USING_ITEM = 25,
    PLAYER_FLAGS = 26,
    PLAYER_INDEX = 27,
    BED_POSITION = 28,
    X_POWER = 29,
    Y_POWER = 30,
    Z_POWER = 31,
    AUX_POWER = 32,
    FISHX = 33,
    FISHZ = 34,
    FISHANGLE = 35,
    AUX_VALUE_DATA = 36,
    LEASH_HOLDER = 37,
    RESERVED_038 = 38,
    HAS_NPC = 39,
    NPC_DATA = 40,
    ACTIONS = 41,
    AIR_SUPPLY_MAX = 42,
    MARK_VARIANT = 43,
    CONTAINER_TYPE = 44,
    CONTAINER_SIZE = 45,
    CONTAINER_STRENGTH_MODIFIER = 46,
    BLOCK_TARGET = 47,
    INV = 48,
    TARGET_A = 49,
    TARGET_B = 50,
    TARGET_C = 51,
    AERIAL_ATTACK = 52,
    RESERVED_053 = 53,
    RESERVED_054 = 54,
    FUSE_TIME = 55,
    RESERVED_056 = 56,
    SEAT_LOCK_PASSENGER_ROTATION = 57,
    SEAT_LOCK_PASSENGER_ROTATION_DEGREES = 58,
    SEAT_ROTATION_OFFSET = 59,
    SEAT_ROTATION_OFFSET_DEGREES = 60,
    DATA_RADIUS = 61,
    DATA_WAITING = 62,
    DATA_PARTICLE = 63,
    PEEK_ID = 64,
    ATTACH_FACE = 65,
    ATTACHED = 66,
    ATTACH_POS = 67,
    TRADE_TARGET = 68,
    CAREER = 69,
    HAS_COMMAND_BLOCK = 70,
    COMMAND_NAME = 71,
    LAST_COMMAND_OUTPUT = 72,
    TRACK_COMMAND_OUTPUT = 73,
    RESERVED_074 = 74,
    STRENGTH = 75,
    STRENGTH_MAX = 76,
    DATA_SPELL_CASTING_COLOR = 77,
    DATA_LIFETIME_TICKS = 78,
    POSE_INDEX = 79,
    DATA_TICK_OFFSET = 80,
    NAMETAG_ALWAYS_SHOW = 81,
    COLOR_2_INDEX = 82,
    NAME_AUTHOR = 83,
    SCORE = 84,
    BALLOON_ANCHOR = 85,
    PUFFED_STATE = 86,
    BUBBLE_TIME = 87,
    AGENT = 88,
    SITTING_AMOUNT = 89,
    SITTING_AMOUNT_PREVIOUS = 90,
    EATING_COUNTER = 91,
    RESERVED_092 = 92,
    LAYING_AMOUNT = 93,
    LAYING_AMOUNT_PREVIOUS = 94,
    DATA_DURATION = 95,
    DATA_SPAWN_TIME_DEPRECATED = 96,
    DATA_CHANGE_RATE = 97,
    DATA_CHANGE_ON_PICKUP = 98,
    DATA_PICKUP_COUNT = 99,
    INTERACT_TEXT = 100,
    TRADE_TIER = 101,
    MAX_TRADE_TIER = 102,
    TRADE_EXPERIENCE = 103,
    SKIN_ID = 104,
    SPAWNING_FRAMES = 105,
    COMMAND_BLOCK_TICK_DELAY = 106,
    COMMAND_BLOCK_EXECUTE_ON_FIRST_TICK = 107,
    AMBIENT_SOUND_INTERVAL = 108,
    AMBIENT_SOUND_INTERVAL_RANGE = 109,
    AMBIENT_SOUND_EVENT_NAME = 110,
    FALL_DAMAGE_MULTIPLIER = 111,
    NAME_RAW_TEXT = 112,
    CAN_RIDE_TARGET = 113,
    LOW_TIER_CURED_TRADE_DISCOUNT = 114,
    HIGH_TIER_CURED_TRADE_DISCOUNT = 115,
    NEARBY_CURED_TRADE_DISCOUNT = 116,
    NEARBY_CURED_DISCOUNT_TIME_STAMP = 117,
    HITBOX = 118,
    IS_BUOYANT = 119,
    FREEZING_EFFECT_STRENGTH = 120,
    BUOYANCY_DATA = 121,
    GOAT_HORN_COUNT = 122,
    BASE_RUNTIME_ID = 123,
    MOVEMENT_SOUND_DISTANCE_OFFSET = 124,
    HEARTBEAT_INTERVAL_TICKS = 125,
    HEARTBEAT_SOUND_EVENT = 126,
    PLAYER_LAST_DEATH_POS = 127,
    PLAYER_LAST_DEATH_DIMENSION = 128,
    PLAYER_HAS_DIED = 129,
    COLLISION_BOX = 130,
    VISIBLE_MOB_EFFECTS = 131,
    FILTERED_NAME = 132,
    ENTER_BED_POSITION = 133,
    SEAT_THIRD_PERSON_CAMERA_RADIUS = 134,
    SEAT_CAMERA_RELAX_DISTANCE_SMOOTHING = 135,
    // Since v924
    AIM_ASSIST_PRIORITY_PRESET_ID = 136,
    AIM_ASSIST_PRIORITY_CATEGORY_ID = 137,
    AIM_ASSIST_PRIORITY_ACTOR_ID = 138,
    Count = 139,
};

/// SharedTypes::Legacy::LevelSoundEvent (enum class : unsigned int in BDS)
enum class LevelSoundEvent : unsigned int {
    ItemUseOn = 0,
    Hit = 1,
    Step = 2,
    Fly = 3,
    Jump = 4,
    Break = 5,
    Place = 6,
    HeavyStep = 7,
    Gallop = 8,
    Fall = 9,
    Ambient = 10,
    AmbientBaby = 11,
    AmbientInWater = 12,
    Breathe = 13,
    Death = 14,
    DeathInWater = 15,
    DeathToZombie = 16,
    Hurt = 17,
    HurtInWater = 18,
    Mad = 19,
    Boost = 20,
    Bow = 21,
    SquishBig = 22,
    SquishSmall = 23,
    FallBig = 24,
    FallSmall = 25,
    Splash = 26,
    Fizz = 27,
    Flap = 28,
    Swim = 29,
    Drink = 30,
    Eat = 31,
    Takeoff = 32,
    Shake = 33,
    Plop = 34,
    Land = 35,
    Saddle = 36,
    Armor = 37,
    ArmorPlace = 38,
    AddChest = 39,
    Throw = 40,
    Attack = 41,
    AttackNoDamage = 42,
    AttackStrong = 43,
    Warn = 44,
    Shear = 45,
    Milk = 46,
    Thunder = 47,
    Explode = 48,
    Fire = 49,
    Ignite = 50,
    Fuse = 51,
    Stare = 52,
    Spawn = 53,
    Shoot = 54,
    BreakBlock = 55,
    Launch = 56,
    Blast = 57,
    LargeBlast = 58,
    Twinkle = 59,
    Remedy = 60,
    Unfect = 61,
    LevelUp = 62,
    BowHit = 63,
    BulletHit = 64,
    ExtinguishFire = 65,
    ItemFizz = 66,
    ChestOpen = 67,
    ChestClosed = 68,
    ShulkerBoxOpen = 69,
    ShulkerBoxClosed = 70,
    EnderChestOpen = 71,
    EnderChestClosed = 72,
    PowerOn = 73,
    PowerOff = 74,
    Attach = 75,
    Detach = 76,
    Deny = 77,
    Tripod = 78,
    Pop = 79,
    DropSlot = 80,
    Note = 81,
    Thorns = 82,
    PistonIn = 83,
    PistonOut = 84,
    Portal = 85,
    Water = 86,
    LavaPop = 87,
    Lava = 88,
    Burp = 89,
    BucketFillWater = 90,
    BucketFillLava = 91,
    BucketEmptyWater = 92,
    BucketEmptyLava = 93,
    EquipChain = 94,
    EquipDiamond = 95,
    EquipGeneric = 96,
    EquipGold = 97,
    EquipIron = 98,
    EquipLeather = 99,
    EquipElytra = 100,
    Record13 = 101,
    RecordCat = 102,
    RecordBlocks = 103,
    RecordChirp = 104,
    RecordFar = 105,
    RecordMall = 106,
    RecordMellohi = 107,
    RecordStal = 108,
    RecordStrad = 109,
    RecordWard = 110,
    Record11 = 111,
    RecordWait = 112,
    RecordNull = 113,
    Flop = 114,
    GuardianCurse = 115,
    MobWarning = 116,
    MobWarningBaby = 117,
    Teleport = 118,
    ShulkerOpen = 119,
    ShulkerClose = 120,
    Haggle = 121,
    HaggleYes = 122,
    HaggleNo = 123,
    HaggleIdle = 124,
    ChorusGrow = 125,
    ChorusDeath = 126,
    Glass = 127,
    PotionBrewed = 128,
    CastSpell = 129,
    PrepareAttackSpell = 130,
    PrepareSummon = 131,
    PrepareWololo = 132,
    Fang = 133,
    Charge = 134,
    TakePicture = 135,
    PlaceLeashKnot = 136,
    BreakLeashKnot = 137,
    AmbientGrowl = 138,
    AmbientWhine = 139,
    AmbientPant = 140,
    AmbientPurr = 141,
    AmbientPurreow = 142,
    DeathMinVolume = 143,
    DeathMidVolume = 144,
    ImitateBlaze = 145,
    ImitateCaveSpider = 146,
    ImitateCreeper = 147,
    ImitateElderGuardian = 148,
    ImitateEnderDragon = 149,
    ImitateEnderman = 150,
    ImitateEndermite = 151,
    ImitateEvocationIllager = 152,
    ImitateGhast = 153,
    ImitateHusk = 154,
    ImitateMagmaCube = 156,
    ImitatePolarBear = 157,
    ImitateShulker = 158,
    ImitateSilverfish = 159,
    ImitateSkeleton = 160,
    ImitateSlime = 161,
    ImitateSpider = 162,
    ImitateStray = 163,
    ImitateVex = 164,
    ImitateVindicationIllager = 165,
    ImitateWitch = 166,
    ImitateWither = 167,
    ImitateWitherSkeleton = 168,
    ImitateWolf = 169,
    ImitateZombie = 170,
    ImitateZombiePigman = 171,
    ImitateZombieVillager = 172,
    EnderEyePlaced = 173,
    EndPortalCreated = 174,
    AnvilUse = 175,
    BottleDragonBreath = 176,
    PortalTravel = 177,
    TridentHit = 178,
    TridentReturn = 179,
    TridentRiptide1 = 180,
    TridentRiptide2 = 181,
    TridentRiptide3 = 182,
    TridentThrow = 183,
    TridentThunder = 184,
    TridentHitGround = 185,
    Default = 186,
    FletchingTableUse = 187,
    ElemConstructOpen = 188,
    IceBombHit = 189,
    BalloonPop = 190,
    LtReactionIceBomb = 191,
    LtReactionBleach = 192,
    LtReactionElephantToothpaste = 193,
    LtReactionElephantToothpaste2 = 194,
    LtReactionGlowStick = 195,
    LtReactionGlowStick2 = 196,
    LtReactionLuminol = 197,
    LtReactionSalt = 198,
    LtReactionFertilizer = 199,
    LtReactionFireball = 200,
    LtReactionMagnesiumSalt = 201,
    LtReactionMiscFire = 202,
    LtReactionFire = 203,
    LtReactionMiscExplosion = 204,
    LtReactionMiscMystical = 205,
    LtReactionMiscMystical2 = 206,
    LtReactionProduct = 207,
    SparklerUse = 208,
    GlowStickUse = 209,
    SparklerActive = 210,
    ConvertToDrowned = 211,
    BucketFillFish = 212,
    BucketEmptyFish = 213,
    BubbleColumnUpwards = 214,
    BubbleColumnDownwards = 215,
    BubblePop = 216,
    BubbleUpInside = 217,
    BubbleDownInside = 218,
    HurtBaby = 219,
    DeathBaby = 220,
    StepBaby = 221,
    SpawnBaby = 222,
    Born = 223,
    TurtleEggBreak = 224,
    TurtleEggCrack = 225,
    TurtleEggHatched = 226,
    LayEgg = 227,
    TurtleEggAttacked = 228,
    BeaconActivate = 229,
    BeaconAmbient = 230,
    BeaconDeactivate = 231,
    BeaconPower = 232,
    ConduitActivate = 233,
    ConduitAmbient = 234,
    ConduitAttack = 235,
    ConduitDeactivate = 236,
    ConduitShort = 237,
    Swoop = 238,
    BambooSaplingPlace = 239,
    PreSneeze = 240,
    Sneeze = 241,
    AmbientTame = 242,
    Scared = 243,
    ScaffoldingClimb = 244,
    CrossbowLoadingStart = 245,
    CrossbowLoadingMiddle = 246,
    CrossbowLoadingEnd = 247,
    CrossbowShoot = 248,
    CrossbowQuickChargeStart = 249,
    CrossbowQuickChargeMiddle = 250,
    CrossbowQuickChargeEnd = 251,
    AmbientAggressive = 252,
    AmbientWorried = 253,
    CantBreed = 254,
    ShieldBlock = 255,
    LecternBookPlace = 256,
    GrindstoneUse = 257,
    Bell = 258,
    CampfireCrackle = 259,
    Roar = 260,
    Stun = 261,
    SweetBerryBushHurt = 262,
    SweetBerryBushPick = 263,
    CartographyTableUse = 264,
    StonecutterUse = 265,
    ComposterEmpty = 266,
    ComposterFill = 267,
    ComposterFillLayer = 268,
    ComposterReady = 269,
    BarrelOpen = 270,
    BarrelClose = 271,
    RaidHorn = 272,
    LoomUse = 273,
    AmbientInRaid = 274,
    UiCartographyTableUse = 275,
    UiStonecutterUse = 276,
    UiLoomUse = 277,
    SmokerUse = 278,
    BlastFurnaceUse = 279,
    SmithingTableUse = 280,
    Screech = 281,
    Sleep = 282,
    FurnaceUse = 283,
    MooshroomConvert = 284,
    MilkSuspiciously = 285,
    Celebrate = 286,
    JumpPrevent = 287,
    AmbientPollinate = 288,
    BeehiveDrip = 289,
    BeehiveEnter = 290,
    BeehiveExit = 291,
    BeehiveWork = 292,
    BeehiveShear = 293,
    HoneybottleDrink = 294,
    AmbientCave = 295,
    Retreat = 296,
    ConvertToZombified = 297,
    Admire = 298,
    StepLava = 299,
    Tempt = 300,
    Panic = 301,
    Angry = 302,
    AmbientMoodWarpedForest = 303,
    AmbientMoodSoulsandValley = 304,
    AmbientMoodNetherWastes = 305,
    AmbientMoodBasaltDeltas = 306,
    AmbientMoodCrimsonForest = 307,
    RespawnAnchorCharge = 308,
    RespawnAnchorDeplete = 309,
    RespawnAnchorSetSpawn = 310,
    RespawnAnchorAmbient = 311,
    SoulEscapeQuiet = 312,
    SoulEscapeLoud = 313,
    RecordPigstep = 314,
    LinkCompassToLodestone = 315,
    UseSmithingTable = 316,
    EquipNetherite = 317,
    AmbientLoopWarpedForest = 318,
    AmbientLoopSoulsandValley = 319,
    AmbientLoopNetherWastes = 320,
    AmbientLoopBasaltDeltas = 321,
    AmbientLoopCrimsonForest = 322,
    AmbientAdditionWarpedForest = 323,
    AmbientAdditionSoulsandValley = 324,
    AmbientAdditionNetherWastes = 325,
    AmbientAdditionBasaltDeltas = 326,
    AmbientAdditionCrimsonForest = 327,
    SculkSensorPowerOn = 328,
    SculkSensorPowerOff = 329,
    BucketFillPowderSnow = 330,
    BucketEmptyPowderSnow = 331,
    PointedDripstoneCauldronDripWater = 332,
    PointedDripstoneCauldronDripLava = 333,
    PointedDripstoneDripWater = 334,
    PointedDripstoneDripLava = 335,
    CaveVinesPickBerries = 336,
    BigDripleafTiltDown = 337,
    BigDripleafTiltUp = 338,
    CopperWaxOn = 339,
    CopperWaxOff = 340,
    Scrape = 341,
    PlayerHurtDrown = 342,
    PlayerHurtOnFire = 343,
    PlayerHurtFreeze = 344,
    UseSpyglass = 345,
    StopUsingSpyglass = 346,
    AmethystBlockChime = 347,
    AmbientScreamer = 348,
    HurtScreamer = 349,
    DeathScreamer = 350,
    MilkScreamer = 351,
    JumpToBlock = 352,
    PreRam = 353,
    PreRamScreamer = 354,
    RamImpact = 355,
    RamImpactScreamer = 356,
    SquidInkSquirt = 357,
    GlowSquidInkSquirt = 358,
    ConvertToStray = 359,
    CakeAddCandle = 360,
    ExtinguishCandle = 361,
    AmbientCandle = 362,
    BlockClick = 363,
    BlockClickFail = 364,
    SculkCatalystBloom = 365,
    SculkShriekerShriek = 366,
    NearbyClose = 367,
    NearbyCloser = 368,
    NearbyClosest = 369,
    Agitated = 370,
    RecordOtherside = 371,
    Tongue = 372,
    CrackIronGolem = 373,
    RepairIronGolem = 374,
    Listening = 375,
    Heartbeat = 376,
    HornBreak = 377,
    SculkSpread = 379,
    SculkCharge = 380,
    SculkSensorPlace = 381,
    SculkShriekerPlace = 382,
    GoatCall0 = 383,
    GoatCall1 = 384,
    GoatCall2 = 385,
    GoatCall3 = 386,
    GoatCall4 = 387,
    GoatCall5 = 388,
    GoatCall6 = 389,
    GoatCall7 = 390,
    ImitateWarden = 426,
    ListeningAngry = 427,
    ItemGiven = 428,
    ItemTaken = 429,
    Disappeared = 430,
    Reappeared = 431,
    DrinkMilk = 432,
    FrogspawnHatched = 433,
    LaySpawn = 434,
    FrogspawnBreak = 435,
    SonicBoom = 436,
    SonicCharge = 437,
    ItemThrown = 438,
    Record5 = 439,
    ConvertToFrog = 440,
    RecordPlaying = 441,
    EnchantingTableUse = 442,
    StepSand = 443,
    DashReady = 444,
    BundleDropContents = 445,
    BundleInsert = 446,
    BundleRemoveOne = 447,
    PressurePlateClickOff = 448,
    PressurePlateClickOn = 449,
    ButtonClickOff = 450,
    ButtonClickOn = 451,
    DoorOpen = 452,
    DoorClose = 453,
    TrapdoorOpen = 454,
    TrapdoorClose = 455,
    FenceGateOpen = 456,
    FenceGateClose = 457,
    Insert = 458,
    Pickup = 459,
    InsertEnchanted = 460,
    PickupEnchanted = 461,
    Brush = 462,
    BrushCompleted = 463,
    ShatterDecoratedPot = 464,
    BreakDecoratedPot = 465,
    SnifferEggCrack = 466,
    SnifferEggHatched = 467,
    WaxedSignInteractFail = 468,
    RecordRelic = 469,
    Bump = 470,
    PumpkinCarve = 471,
    ConvertHuskToZombie = 472,
    PigDeath = 473,
    HoglinConvertToZombified = 474,
    AmbientUnderwaterEnter = 475,
    AmbientUnderwaterExit = 476,
    BottleFill = 477,
    BottleEmpty = 478,
    CrafterCraft = 479,
    CrafterFail = 480,
    DecoratedPotInsert = 481,
    DecoratedPotInsertFail = 482,
    CrafterDisableSlot = 483,
    TrialSpawnerOpenShutter = 484,
    TrialSpawnerEjectItem = 485,
    TrialSpawnerDetectPlayer = 486,
    TrialSpawnerSpawnMob = 487,
    TrialSpawnerCloseShutter = 488,
    TrialSpawnerAmbient = 489,
    CopperBulbTurnOn = 490,
    CopperBulbTurnOff = 491,
    AmbientInAir = 492,
    BreezeWindChargeBurst = 493,
    ImitateBreeze = 494,
    ArmadilloBrush = 495,
    ArmadilloScuteDrop = 496,
    EquipWolf = 497,
    UnequipWolf = 498,
    Reflect = 499,
    VaultOpenShutter = 500,
    VaultCloseShutter = 501,
    VaultEjectItem = 502,
    VaultInsertItem = 503,
    VaultInsertItemFail = 504,
    VaultAmbient = 505,
    VaultActivate = 506,
    VaultDeactivate = 507,
    HurtReduced = 508,
    WindChargeBurst = 509,
    ImitateBogged = 510,
    WolfArmorCrack = 511,
    WolfArmorBreak = 512,
    WolfArmorRepair = 513,
    MaceSmashAir = 514,
    MaceSmashGround = 515,
    TrialSpawnerChargeActivate = 516,
    TrialSpawnerAmbientOminous = 517,
    OminousItemSpawnerSpawnItem = 518,
    OminousBottleEndUse = 519,
    MaceHeavySmashGround = 520,
    OminousItemSpawnerSpawnItemBegin = 521,
    ApplyEffectBadOmen = 523,
    ApplyEffectRaidOmen = 524,
    ApplyEffectTrialOmen = 525,
    OminousItemSpawnerAboutToSpawnItem = 526,
    RecordCreator = 527,
    RecordCreatorMusicBox = 528,
    RecordPrecipice = 529,
    VaultRejectRewardedPlayer = 530,
    ImitateDrowned = 531,
    ImitateCreaking = 532,
    BundleInsertFail = 533,
    SpongeAbsorb = 534,
    CreakingHeartTrail = 536,
    CreakingHeartSpawn = 537,
    Activate = 538,
    Deactivate = 539,
    Freeze = 540,
    Unfreeze = 541,
    Open = 542,
    OpenLong = 543,
    Close = 544,
    CloseLong = 545,
    ImitatePhantom = 546,
    ImitateZoglin = 547,
    ImitateGuardian = 548,
    ImitateRavager = 549,
    ImitatePillager = 550,
    PlaceInWater = 551,
    StateChange = 552,
    ImitateHappyGhast = 553,
    UnequipGeneric = 554,
    RecordTears = 555,
    TheEndLightFlash = 556,
    LeadLeash = 557,
    LeadUnleash = 558,
    LeadBreak = 559,
    Unsaddle = 560,
    EquipCopper = 561,
    RecordLavaChicken = 562,
    PlaceItem = 563,
    SingleItemSwap = 564,
    MultiItemSwap = 565,
    // Since v860
    Lunge1 = 566,
    Lunge2 = 567,
    Lunge3 = 568,
    AttackCritical = 569,
    SpearAttackHit = 570,
    SpearAttackMiss = 571,
    WoodenSpearAttackHit = 572,
    WoodenSpearAttackMiss = 573,
    ImitateParched = 574,
    ImitateCamelHusk = 575,
    SpearUse = 576,
    WoodenSpearUse = 577,
    // Since v924
    SaddleInWater = 578,
    StoneSpearAttackHit = 579,
    IronSpearAttackHit = 580,
    CopperSpearAttackHit = 581,
    GoldenSpearAttackHit = 582,
    DiamondSpearAttackHit = 583,
    NetheriteSpearAttackHit = 584,
    StoneSpearAttackMiss = 585,
    IronSpearAttackMiss = 586,
    CopperSpearAttackMiss = 587,
    GoldenSpearAttackMiss = 588,
    DiamondSpearAttackMiss = 589,
    NetheriteSpearAttackMiss = 590,
    StoneSpearUse = 591,
    IronSpearUse = 592,
    CopperSpearUse = 593,
    GoldenSpearUse = 594,
    DiamondSpearUse = 595,
    NetheriteSpearUse = 596,
    // Since v944
    PauseGrowth = 597,
    ResetGrowth = 598,
    Undefined = 599,
};

/// SynchedActorData DataItemType (byte in BDS)
enum class DataItemType : std::uint8_t {
    Byte = 0,
    Short = 1,
    Int = 2,
    Float = 3,
    String = 4,
    CompoundTag = 5,
    Pos = 6,
    Int64 = 7,
    Vec3 = 8,
    Unknown = 9,
};

/// CommandOriginData::CommandOriginType
enum class CommandOriginType : std::uint8_t {
    Player = 0,
    CommandBlock = 1,
    MinecartCommandBlock = 2,
    DevConsole = 3,
    Test = 4,
    AutomationPlayer = 5,
    ClientAutomation = 6,
    DedicatedServer = 7,
    Entity = 8,
    Virtual = 9,
    GameArgument = 10,
    EntityServer = 11,
    Precompiled = 12,
    GameDirectorEntityServer = 13,
    Scripting = 14,
    ExecuteContext = 15,
};

/// CommandOutput::CommandOutputType
enum class CommandOutputType : int {
    None = 0,
    LastOutput = 1,
    Silent = 2,
    AllOutput = 3,
    DataSet = 4,
};

/// CommandPermissionLevel
enum class CommandPermissionLevel : std::uint8_t {
    Any = 0,
    GameDirectors = 1,
    Admin = 2,
    Host = 3,
    Owner = 4,
    Internal = 5,
};

/// CommandVersion CurrentCmdVersion (subset used by endweave)
enum class CurrentCmdVersion : std::int32_t {
    Invalid = -1,
    Initial = 1,
    PostBlockFlattening = 43,
    TestForBlockDoesNotIgnoreBlockState = 44,
    CloneExtraBlockFilterFix = 45,
};

/// InventorySource InventorySourceType
enum class InventorySourceType : std::uint32_t {
    InvalidInventory = 4294967295u,
    ContainerInventory = 0,
    GlobalInventory = 1,
    WorldInteraction = 2,
    CreativeInventory = 3,
    NonImplementedFeatureTODO = 99999,
};

/// TextPacketType (byte in BDS)
enum class TextPacketType : std::uint8_t {
    Raw = 0,
    Chat = 1,
    Translate = 2,
    Popup = 3,
    JukeboxPopup = 4,
    Tip = 5,
    SystemMessage = 6,
    Whisper = 7,
    Announcement = 8,
    TextObjectWhisper = 9,
    TextObject = 10,
    TextObjectAnnouncement = 11,
};

/// ComplexInventoryTransaction::Type
enum class ComplexInventoryTransactionType : std::uint32_t {
    NormalTransaction = 0,
    InventoryMismatch = 1,
    ItemUseTransaction = 2,
    ItemUseOnEntityTransaction = 3,
    ItemReleaseTransaction = 4,
};

/// InteractPacketPayload::Action
enum class InteractAction : std::uint8_t {
    Invalid = 0,
    StopRiding = 3,
    InteractUpdate = 4,
    NpcOpen = 5,
    OpenInventory = 6,
};

/// AnimatePacketPayload::Action
enum class AnimateAction : std::uint8_t {
    NoAction = 0,
    Swing = 1,
    WakeUp = 3,
    CriticalHit = 4,
    MagicCriticalHit = 5,
};

/// ClientboundMapItemDataPacket::Type (bitmask flags)
enum class ClientboundMapItemDataType : std::int32_t {
    Invalid = 0,
    TextureUpdate = 2,
    DecorationUpdate = 4,
    Creation = 8,
};

/// MapItemTrackedActor::Type
enum class MapItemTrackedActorType : int {
    Entity = 0,
    BlockEntity = 1,
    Other = 2,
};

/// GameRule::Type
enum class GameRuleType : std::uint8_t {
    Invalid = 0,
    Bool = 1,
    Int = 2,
    Float = 3,
};

/// BookEditPacketPayload variant index (std::variant in BDS)
enum class BookEditActionType : std::uint8_t {
    ReplacePage = 0,
    AddPage = 1,
    DeletePage = 2,
    SwapPages = 3,
    Finalize = 4,
};

/// TextPacketPayload::mBody variant index (std::variant in BDS)
enum class TextPacketBodyType : std::uint8_t {
    MessageOnly = 0,
    AuthorAndMessage = 1,
    MessageAndParams = 2,
};

// -- LevelSoundEvent version boundaries --
// First ID introduced in each protocol version,
// used by SoundRewriter to clamp/remap across version gaps.

namespace sound_boundaries {

// v860 start (v859 ends at MultiItemSwap = 565)
inline constexpr unsigned int v860_start = 566; // Lunge1

// v898 start (v860 ends at WoodenSpearUse = 577)
inline constexpr unsigned int v898_start = 578; // SaddleInWater

// v944 start (v924 ends at NetheriteSpearUse = 596)
inline constexpr unsigned int v944_start = 597; // PauseGrowth

// Undefined/max
inline constexpr unsigned int undefined = 599;

} // namespace sound_boundaries

} // namespace endweave
