"""Regenerate the sparse 26.40/26.50 hash tables (maintainer dependency: amulet-nbt).

Usage: python tools/generate_block_mappings.py palette-2168.nbt palette-2193.nbt blocks.json
Palettes are gzip-compressed big-endian NBT from CloudburstMC/Data (Apache-2.0):
2168: 247e816d1de47479dd163709192d1f7679005208/block_palette.nbt
2193: 7046791ae9fcf056a3b26cd6605ffc1db6d97357/block_palette.nbt
Geometry: 7046791ae9fcf056a3b26cd6605ffc1db6d97357/blocks.json
"""

import hashlib
import json
import sys
from pathlib import Path

import amulet_nbt

EXPECTED = (
    "26826e766aa0916d757706adbbb53da0f548308a14ab0ff389db9dec9b297aca",
    "54c9bed0bef30aadc316b21c6e82b5ac407c5c6e351b9d9690aa4e9a49fec912",
)
ADDED = {"minecraft:corner": "none", **{f"minecraft:connection_{d}": 0 for d in ("north", "east", "south", "west")}}


def read(path: Path, digest: str) -> dict:
    assert hashlib.sha256(path.read_bytes()).hexdigest() == digest, path
    blocks = amulet_nbt.load(str(path)).compound["blocks"]
    return {
        (str(b["name"]), tuple(sorted((k, v.py_data) for k, v in b["states"].items()))): int(b["network_id"])
        & 0xFFFFFFFF
        for b in blocks
    }


def main() -> None:
    old, new = (read(Path(p), digest) for p, digest in zip(sys.argv[1:3], EXPECTED, strict=True))
    up, down = {}, {}
    for (name, states), runtime_id in new.items():
        legacy_key = (name, tuple((k, v) for k, v in states if k not in ADDED))
        # A new block type has no old-server equivalent; only migrate existing types.
        if legacy_key not in old:
            continue
        legacy_id = old[legacy_key]
        if runtime_id != legacy_id:
            down[runtime_id] = legacy_id
        if all(v == ADDED[k] for k, v in states if k in ADDED):
            if runtime_id != legacy_id:
                up[legacy_id] = runtime_id
    assert all(key in new or runtime_id in up for key, runtime_id in old.items())
    assert all(runtime_id == new[key] for key, runtime_id in old.items() if key in new)
    target = Path(__file__).resolve().parents[1] / "src/endweave/protocols/block_mappings.inc"
    text = "// Generated by tools/generate_block_mappings.py from CloudburstMC/Data (Apache-2.0).\n"
    text += "// See tools/generate_block_mappings.py for pinned sources and checksums.\n"
    for name, rows in (("kBlocksTo2193", up), ("kBlocksTo2168", down)):
        text += f"static constexpr std::array<BlockMapping, {len(rows)}> {name} = {{{{\n"
        text += "".join(f"    {{{a}u, {b}u}},\n" for a, b in sorted(rows.items()))
        text += "}};\n"
    target.write_text(text, encoding="utf-8")
    attributes = Path(sys.argv[3])
    assert hashlib.sha256(attributes.read_bytes()).hexdigest() == (
        "d8d64e738c4ce74ff3e5cfec6710fe94eb4ab771deaf5d430bc81b5bb2205fc5"
    )
    geometry = {b["blockStateHash"]: b for b in json.loads(attributes.read_text())}
    shapes, connections = [], []
    for (name, state_items), runtime_id in old.items():
        states = dict(state_items)
        kind = 0
        facing = 0
        if name.endswith("_stairs"):
            kind = 1
            facing = (1, 3, 2, 0)[states["weirdo_direction"]]
        elif name.endswith("_fence"):
            kind = 3 if name == "minecraft:nether_brick_fence" else 2
        elif "glass_pane" in name or name.endswith("_bars"):
            kind = 4
        elif name == "minecraft:trip_wire":
            kind = 5
        elif name.endswith("fence_gate"):
            kind = 6
            facing = ("north", "east", "south", "west").index(states["minecraft:cardinal_direction"])
        elif name == "minecraft:tripwire_hook":
            kind = 7
            facing = (states["direction"] + 2) % 4
        faces = 0
        boxes = geometry[runtime_id]["collisionShape"] or []
        for face, axis, plane in ((0, 2, 0), (1, 0, 1), (2, 2, 1), (3, 0, 0)):
            other = 2 if axis == 0 else 0
            rectangles = [(b[other], b[1], b[other + 3], b[4]) for b in boxes if b[axis] <= plane <= b[axis + 3]]
            xs = sorted({0, 1, *(v for r in rectangles for v in (r[0], r[2]) if 0 < v < 1)})
            ys = sorted({0, 1, *(v for r in rectangles for v in (r[1], r[3]) if 0 < v < 1)})
            if all(
                any(a <= (x0 + x1) / 2 <= c and b <= (y0 + y1) / 2 <= d for a, b, c, d in rectangles)
                for x0, x1 in zip(xs, xs[1:])
                for y0, y1 in zip(ys, ys[1:])
            ):
                faces |= 1 << face
        if "leaves" in name:  # Foliage is not a fence support despite its collision cube.
            faces = 0
        if kind or faces:
            shapes.append((runtime_id, kind, facing, int(states.get("upside_down_bit", 0)), faces))
        if runtime_id in up:
            variants = []
            for variant in range(5 if kind == 1 else 16):
                added = (
                    {"minecraft:corner": ("none", "inner_left", "inner_right", "outer_left", "outer_right")[variant]}
                    if kind == 1
                    else {
                        f"minecraft:connection_{d}": int(bool(variant & (1 << i)))
                        for i, d in enumerate(("north", "east", "south", "west"))
                    }
                )
                variants.append(new[(name, tuple(sorted((states | added).items())))])
            connections.append((runtime_id, variants))
    text = "// Generated from the pinned CloudburstMC/Data palettes and blocks.json (Apache-2.0).\n"
    text += f"static constexpr std::array<BlockShape, {len(shapes)}> kShapes = {{{{\n"
    text += "".join(f"    {{{i}u, {k}, {d}, {h}, {f}}},\n" for i, k, d, h, f in sorted(shapes)) + "}};\n"
    text += f"static constexpr std::array<ConnectedBlock, {len(connections)}> kConnections = {{{{\n"
    text += (
        "".join(
            "    {" + str(i) + "u, {" + ", ".join(str(v) + "u" for v in values) + "}},\n"
            for i, values in sorted(connections)
        )
        + "}};\n"
    )
    target.with_name("block_connections.inc").write_text(text, encoding="utf-8")
    print(f"Generated {len(up)} forward and {len(down)} reverse mappings; all {len(old)} old states covered.")


if __name__ == "__main__":
    main()
